#!/bin/bash

input="$1"

# TODO Check if ol is installed
# TODO Check if jq is installed
# Use ol to get book info from isbn
out() {
  local a=$1
  info=$(ol --get-book --isbn "$a")
  echo "$info" | jq .authors.[].name,.title,.copyright_date | tr '\n' ',' | sed '$s/,$/\n/' >>/tmp/test
}

while IFS= read -r line; do
  out "$line"
  sleep 0.01
done <"$input"

# TODO Sort all entries of Input file with isbn on each line

cat /tmp/test
rm /tmp/test
